In [3]:
# %pip install torch
import torch
import torch.nn as nn

In [4]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0])
neuron = nn.Linear(in_features=10, out_features=1)
output = neuron(inputs)

In [5]:
output

tensor([2.6147], grad_fn=<ViewBackward0>)

In [6]:
# verify ... formula
neuron.weight @ inputs + neuron.bias

tensor([2.6147], grad_fn=<AddBackward0>)

In [7]:
neuron.bias

Parameter containing:
tensor([0.2749], requires_grad=True)