# ***Numpy Lecture No 01***

In [3]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import time

size = 10000000
list1 = list(range(size))
start = time.time()
squared_list = [x**2 for x in list1]
end = time.time()
print("Time taken using list comprehension:", end - start)

array1 = np.arange(size)
start = time.time()
squared_array = array1 ** 2
end = time.time()
print("Time taken using NumPy array:", end - start)

Time taken using list comprehension: 2.313565254211426
Time taken using NumPy array: 0.05261588096618652


In [7]:
import sys 
print("Size of list1:", sys.getsizeof(list1) * len(list1), "bytes")
print("Size of array1:", array1.nbytes, "bytes")

Size of list1: 800000560000000 bytes
Size of array1: 80000000 bytes


In [9]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array Shape:", arr1.shape)
print("Array Data Type:", arr1.dtype)
print("Array Dimensions:", arr1.ndim)
print("Array Size:", arr1.size)
print(arr1)

Array Shape: (2, 3)
Array Data Type: int64
Array Dimensions: 2
Array Size: 6
[[1 2 3]
 [4 5 6]]


In [14]:
arr1 = np.zeros((3,3))
print("Zeros Array:\n", arr1)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
arr2 = np.ones((2,4))
print("Ones Array:\n", arr2)

arr3 = np.full((2,3), 7)
print("Full Array:\n", arr3)  

arr4 = np.eye(4)
print("Identity-like Array:\n", arr4)  

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]]
Identity-like Array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
str_arr = np.array([1, 2, 3], dtype="float32") 
print(str_arr, str_arr.dtype)

float_arr = np.array([1.5, 2.5, 3.5])
int_arr = float_arr.astype('int32')
print(int_arr, int_arr.dtype)


[1. 2. 3.] float32
[1 2 3] int32


In [32]:
arr = np.array([1,2,3,4,5,6,7,8])
arr_reshaped = arr.reshape((4,2))
print("Reshaped Array:\n", arr_reshaped)

print(arr_reshaped[2,1])

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
6


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]])
print("Original Array:\n", arr)

print("First Row:", arr[0])
print(arr[1,0])

Original Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
First Row: [1 2 3]
4


In [43]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]],[[9,10],[11,12]]])
print("Original 3D Array:\n", arr)

print(arr[0,1,1])
print(arr[2,1,1])
print(arr[1,1,0])
print(arr[1,:,1])
print(arr[:,0,0])

Original 3D Array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
4
12
7
[6 8]
[1 5 9]


In [52]:
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
print("Original Array:\n", arr)
print("Array dtype:", arr.ndim)

print(arr[1,0,2])
arr[1,1,2] = 99
print("Modified Array:\n", arr)

Original Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
Array dtype: 3
9
Modified Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 99]]]


In [55]:
arr = np.arange(1,51)
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.median(arr))

1275
25.5
14.430869689661812
208.25
1
0
50
49
25.5
